version: "3.7"

services:
  phpunit:
    build:
      dockerfile: ./docker/PhpUnit.Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    command:
      - composer
      - coverage
    restart: "no"